In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully!")

Libraries imported successfully!

In [11]:
print("Columns:")
print(train_df.columns)

print("\nDataset information:")
train_df.info()

Columns:

NameError: name 'train_df' is not defined

In [ ]:
print("Missing values:")
print(train_df.isnull().sum())

Missing values:
id       0
title    0
genre    0
plot     0
dtype: int64

In [ ]:
print("Genre distribution:")
print(train_df["genre"].value_counts())

Genre distribution:
genre
: drama           13613
: documentary     13096
: comedy           7447
: short            5072
: horror           2204
: thriller         1591
: action           1315
: western          1032
: reality-tv        884
: family            784
: adventure         775
: music             731
: romance           672
: sci-fi            647
: adult             590
: crime             505
: animation         498
: sport             432
: talk-show         391
: fantasy           323
: mystery           319
: musical           277
: biography         265
: history           243
: game-show         194
: news              181
: war               132
Name: count, dtype: int64

In [ ]:
print("Genre distribution:")
print(train_df["genre"].value_counts())

Genre distribution:
genre
: drama           13613
: documentary     13096
: comedy           7447
: short            5072
: horror           2204
: thriller         1591
: action           1315
: western          1032
: reality-tv        884
: family            784
: adventure         775
: music             731
: romance           672
: sci-fi            647
: adult             590
: crime             505
: animation         498
: sport             432
: talk-show         391
: fantasy           323
: mystery           319
: musical           277
: biography         265
: history           243
: game-show         194
: news              181
: war               132
Name: count, dtype: int64

In [ ]:
print(train_df.columns.tolist())
print(test_df.columns.tolist())

['id', 'title', 'genre', 'plot']
['id', 'title', 'genre', 'plot']

In [ ]:
train_df = train_df.drop(columns=["id", "title"])
test_df = test_df.drop(columns=["id", "title"])

print(train_df.head())

         genre                                               plot
0     : drama   : Listening in to a conversation between his d...
1  : thriller   : A brother and sister with a past incestuous ...
2     : adult   : As the bus empties the students for their fi...
3     : drama   : To help their unemployed father make ends me...
4     : drama   : The film's title refers not only to the un-r...

In [ ]:
print("Training missing values:")
print(train_df.isnull().sum())

print("\nTesting missing values:")
print(test_df.isnull().sum())

Training missing values:
genre    0
plot     0
dtype: int64

Testing missing values:
genre        0
plot     54199
dtype: int64

In [ ]:
print("Training missing values:")
print(train_df.isnull().sum())

print("\nTesting missing values:")
print(test_df.isnull().sum())

Training missing values:
genre    0
plot     0
dtype: int64

Testing missing values:
genre        0
plot     54199
dtype: int64

In [ ]:
print("Training missing values:")
print(train_df.isnull().sum())

print("\nTesting missing values:")
print(test_df.isnull().sum())

Training missing values:
genre    0
plot     0
dtype: int64

Testing missing values:
genre        0
plot     54199
dtype: int64

In [ ]:
train_df = train_df.dropna(subset=["plot", "genre"])
test_df = test_df.dropna(subset=["plot", "genre"])

print("Training shape after cleaning:", train_df.shape)
print("Testing shape after cleaning:", test_df.shape)

Training shape after cleaning: (54213, 2)
Testing shape after cleaning: (1, 2)

In [ ]:
train_df["plot"] = train_df["plot"].astype(str).str.lower()
test_df["plot"] = test_df["plot"].astype(str).str.lower()

print(train_df["plot"].head())

0    : listening in to a conversation between his d...
1    : a brother and sister with a past incestuous ...
2    : as the bus empties the students for their fi...
3    : to help their unemployed father make ends me...
4    : the film's title refers not only to the un-r...
Name: plot, dtype: str

In [ ]:
train_df["plot"] = train_df["plot"].astype(str).str.lower()
test_df["plot"] = test_df["plot"].astype(str).str.lower()

print(train_df["plot"].head())

0    : listening in to a conversation between his d...
1    : a brother and sister with a past incestuous ...
2    : as the bus empties the students for their fi...
3    : to help their unemployed father make ends me...
4    : the film's title refers not only to the un-r...
Name: plot, dtype: str

In [ ]:
train_df = train_df.dropna(subset=["plot", "genre"])
test_df = test_df.dropna(subset=["plot", "genre"])

print("Training shape after cleaning:", train_df.shape)
print("Testing shape after cleaning:", test_df.shape)

Training shape after cleaning: (54213, 2)
Testing shape after cleaning: (1, 2)

In [ ]:
train_df["plot"] = train_df["plot"].astype(str).str.lower()
test_df["plot"] = test_df["plot"].astype(str).str.lower()

print(train_df["plot"].head())

0    : listening in to a conversation between his d...
1    : a brother and sister with a past incestuous ...
2    : as the bus empties the students for their fi...
3    : to help their unemployed father make ends me...
4    : the film's title refers not only to the un-r...
Name: plot, dtype: str

In [ ]:
X_train = train_df["plot"]
y_train = train_df["genre"]

X_test = test_df["plot"]
y_test = test_df["genre"]

print("Training text samples:", len(X_train))
print("Training labels:", len(y_train))
print("Testing text samples:", len(X_test))
print("Testing labels:", len(y_test))

Training text samples: 54213
Training labels: 54213
Testing text samples: 1
Testing labels: 1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=50000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF training shape:", X_train_tfidf.shape)
print("TF-IDF testing shape:", X_test_tfidf.shape)

TF-IDF training shape: (54213, 50000)
TF-IDF testing shape: (1, 50000)

## 🔤 TF-IDF Feature Extraction

TF-IDF (Term Frequency-Inverse Document Frequency) is used to convert movie plot text into numerical features that can be processed by machine learning algorithms.

The vectorizer uses unigrams and bigrams while removing common English stop words.

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

print("Models imported successfully!")

Models imported successfully!

In [ ]:
train_path = "../data/train_data.txt"
test_path = "../data/test_data.txt"

train_df = pd.read_csv(
    train_path,
    sep=":::",
    engine="python",
    header=None,
    names=["id", "title", "genre", "plot"],
    on_bad_lines="skip"
)

test_df = pd.read_csv(
    test_path,
    sep=":::",
    engine="python",
    header=None,
    names=["id", "title", "genre", "plot"],
    on_bad_lines="skip"
)

# Convert text columns to strings
for df in [train_df, test_df]:
    df["title"] = df["title"].fillna("").astype(str).str.strip()
    df["genre"] = df["genre"].fillna("").astype(str).str.strip()
    df["plot"] = df["plot"].fillna("").astype(str).str.strip()

print("Training dataset shape:", train_df.shape)
print("Testing dataset shape:", test_df.shape)

print("\nFirst 5 rows:")
print(train_df.head())

Training dataset shape: (54214, 4)
Testing dataset shape: (54200, 4)

First 5 rows:
   id                             title     genre  \
0   1      Oscar et la dame rose (2009)     drama
1   2                      Cupid (1997)  thriller
2   3  Young, Wild and Wonderful (1980)     adult
3   4             The Secret Sin (1915)     drama
4   5            The Unrecovered (2007)     drama

                                                plot
0  Listening in to a conversation between his doc...
1  A brother and sister with a past incestuous re...
2  As the bus empties the students for their fiel...
3  To help their unemployed father make ends meet...
4  The film's title refers not only to the un-rec...

In [ ]:
print("Columns:")
print(train_df.columns.tolist())

print("\nFirst row:")
print(train_df.iloc[0])

print("\nGenre examples:")
print(train_df["genre"].head(10).tolist())

Columns:
['id', 'title', 'genre', 'plot']

First row:
id                                                       1
title                         Oscar et la dame rose (2009)
genre                                                drama
plot     Listening in to a conversation between his doc...
Name: 0, dtype: object

Genre examples:
['drama', 'thriller', 'adult', 'drama', 'drama', 'documentary', 'comedy', 'crime', 'reality-tv', 'horror']

In [ ]:
print("Missing values:")
print(train_df.isnull().sum())

print("\nTest dataset missing values:")
print(test_df.isnull().sum())

Missing values:
id       0
title    0
genre    0
plot     0
dtype: int64

Test dataset missing values:
id       0
title    0
genre    0
plot     0
dtype: int64

In [ ]:
# Remove missing values from important columns
train_df = train_df.dropna(subset=["plot", "genre"])
test_df = test_df.dropna(subset=["plot", "genre"])

# Convert text to lowercase
train_df["plot"] = train_df["plot"].str.lower()
test_df["plot"] = test_df["plot"].str.lower()

print("Training shape after cleaning:", train_df.shape)
print("Testing shape after cleaning:", test_df.shape)

Training shape after cleaning: (54214, 4)
Testing shape after cleaning: (54200, 4)

In [ ]:
X_train = train_df["plot"]
y_train = train_df["genre"]

X_test = test_df["plot"]
y_test = test_df["genre"]

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (54214,)
y_train: (54214,)
X_test: (54200,)
y_test: (54200,)

## 🔤 TF-IDF Feature Extraction

TF-IDF converts movie plot summaries into numerical features that machine learning models can understand.

We use unigrams and bigrams and remove common English stop words.

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

print("Models imported successfully!")

Models imported successfully!

In [ ]:
naive_bayes_model = MultinomialNB()

naive_bayes_model.fit(X_train_tfidf, y_train)

print("Naive Bayes training completed!")

Naive Bayes training completed!

In [ ]:
logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_tfidf, y_train)

print("Logistic Regression training completed!")

Logistic Regression training completed!

In [ ]:
svm_model = LinearSVC(
    max_iter=2000,
    random_state=42
)

svm_model.fit(X_train_tfidf, y_train)

print("SVM training completed!")

SVM training completed!

In [ ]:
nb_pred = naive_bayes_model.predict(X_test_tfidf)
logistic_pred = logistic_model.predict(X_test_tfidf)
svm_pred = svm_model.predict(X_test_tfidf)

print("Predictions completed!")

Predictions completed!

In [ ]:
comparison_df = pd.DataFrame({
    "Actual Genre": y_test.values[:20],
    "Naive Bayes": nb_pred[:20],
    "Logistic Regression": logistic_pred[:20],
    "SVM": svm_pred[:20]
})

comparison_df

,Actual Genre,Naive Bayes,Logistic Regression,SVM
0,"L.R. Brane loves his life - his car, his apart...",drama,short,short
1,"Spain, March 1964: Quico is a very naughty chi...",drama,short,short
2,One year in the life of Albin and his family o...,drama,short,short
3,"His father has died, he hasn't spoken with his...",drama,short,short
4,Before he was known internationally as a marti...,drama,short,short
5,Emily Burns is being held captive in a room wi...,drama,short,short
6,The beautiful but neglected wife of a brillian...,drama,short,short
7,Vasu Inamdar (Ina) suffers from a disorder whe...,drama,short,short
8,An insight into the tornados that hit Kensal R...,drama,short,short
9,Press is a story of young people overwhelmed b...,drama,short,short
10,Not much is known about the firm for which bus...,drama,short,short
11,"After a year traveling the world, twentysometh...",drama,short,short
12,"Young-ja initially mocks the shy, introverted ...",drama,short,short
13,"Mark Chambers, a down and out former professio...",drama,short,short
14,On the night a husband finally brings himself ...,drama,short,short
15,Ex-Formula 1 rookie of the year and Motor Raci...,drama,short,short
16,Ma and Pa do their bit to hook lumberman Brad ...,drama,short,short
17,"Bob Wiley, a veteran and a patriot, discovers ...",drama,short,short
18,"Eugen Sandow was a German strongman, circus pe...",drama,short,short
19,Joseph Jacoby introduces himself. He's a write...,drama,short,short

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(name, y_true, y_pred):
    return {
        "Model": name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(
            y_true, y_pred,
            average="weighted",
            zero_division=0
        ),
        "Recall": recall_score(
            y_true, y_pred,
            average="weighted",
            zero_division=0
        ),
        "F1-Score": f1_score(
            y_true, y_pred,
            average="weighted",
            zero_division=0
        )
    }

results = [
    evaluate_model("Naive Bayes", y_test, nb_pred),
    evaluate_model("Logistic Regression", y_test, logistic_pred),
    evaluate_model("SVM", y_test, svm_pred)
]

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    "F1-Score",
    ascending=False
)

results_df

                 Model  Accuracy  Precision  Recall  F1-Score
0          Naive Bayes       0.0        0.0     0.0       0.0
1  Logistic Regression       0.0        0.0     0.0       0.0
2                  SVM       0.0        0.0     0.0       0.0

In [ ]:
best_model_name = results_df.iloc[0]["Model"]

print("Best Model:", best_model_name)
print("Best F1-Score:", results_df.iloc[0]["F1-Score"])

Best Model: Naive Bayes
Best F1-Score: 0.0

In [ ]:
results_df.round(4)

                 Model  Accuracy  Precision  Recall  F1-Score
0          Naive Bayes       0.0        0.0     0.0       0.0
1  Logistic Regression       0.0        0.0     0.0       0.0
2                  SVM       0.0        0.0     0.0       0.0

In [ ]:
model_dict = {
    "Naive Bayes": naive_bayes_model,
    "Logistic Regression": logistic_model,
    "SVM": svm_model
}

best_model = model_dict[best_model_name]

print("Selected model:", best_model_name)

Selected model: Naive Bayes

In [ ]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(best_model, "../models/best_movie_genre_model.pkl")
joblib.dump(tfidf, "../models/tfidf_vectorizer.pkl")

results_df.to_csv(
    "../models/model_comparison.csv",
    index=False
)

print("Model, TF-IDF vectorizer, and results saved successfully!")

Model, TF-IDF vectorizer, and results saved successfully!

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

print("Models imported successfully!")

Models imported successfully!

In [ ]:
import pandas as pd

train_path = "../data/train_data.txt"
test_path = "../data/test_data.txt"

train_df = pd.read_csv(
    train_path,
    sep=":::",
    engine="python",
    header=None,
    names=["id", "title", "genre", "plot"],
    on_bad_lines="skip"
)

test_df = pd.read_csv(
    test_path,
    sep=":::",
    engine="python",
    header=None,
    names=["id", "title", "genre", "plot"],
    on_bad_lines="skip"
)

for df in [train_df, test_df]:
    df["title"] = df["title"].fillna("").astype(str).str.strip()
    df["genre"] = df["genre"].fillna("").astype(str).str.strip()
    df["plot"] = df["plot"].fillna("").astype(str).str.strip()

print("Training dataset shape:", train_df.shape)
print("Testing dataset shape:", test_df.shape)

print(train_df.head())

Training dataset shape: (54214, 4)
Testing dataset shape: (54200, 4)
   id                             title     genre  \
0   1      Oscar et la dame rose (2009)     drama
1   2                      Cupid (1997)  thriller
2   3  Young, Wild and Wonderful (1980)     adult
3   4             The Secret Sin (1915)     drama
4   5            The Unrecovered (2007)     drama

                                                plot
0  Listening in to a conversation between his doc...
1  A brother and sister with a past incestuous re...
2  As the bus empties the students for their fiel...
3  To help their unemployed father make ends meet...
4  The film's title refers not only to the un-rec...

In [ ]:
train_df = train_df.dropna(subset=["plot", "genre"])
test_df = test_df.dropna(subset=["plot", "genre"])

train_df["plot"] = train_df["plot"].str.lower()
test_df["plot"] = test_df["plot"].str.lower()

print("Training shape:", train_df.shape)
print("Testing shape:", test_df.shape)

Training shape: (54214, 4)
Testing shape: (54200, 4)

In [ ]:
X_train = train_df["plot"]
y_train = train_df["genre"]

X_test = test_df["plot"]
y_test = test_df["genre"]

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (54214,)
y_train: (54214,)
X_test: (54200,)
y_test: (54200,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=50000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF training shape:", X_train_tfidf.shape)
print("TF-IDF testing shape:", X_test_tfidf.shape)

TF-IDF training shape: (54214, 50000)
TF-IDF testing shape: (54200, 50000)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

print("Models imported successfully!")

Models imported successfully!

In [ ]:
naive_bayes_model = MultinomialNB()

naive_bayes_model.fit(X_train_tfidf, y_train)

print("Naive Bayes training completed!")

Naive Bayes training completed!

In [ ]:
logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_tfidf, y_train)

print("Logistic Regression training completed!")

Logistic Regression training completed!

In [ ]:
svm_model = LinearSVC(
    max_iter=2000,
    random_state=42
)

svm_model.fit(X_train_tfidf, y_train)

print("SVM training completed!")

SVM training completed!

In [ ]:
nb_pred = naive_bayes_model.predict(X_test_tfidf)
logistic_pred = logistic_model.predict(X_test_tfidf)
svm_pred = svm_model.predict(X_test_tfidf)

print("Predictions completed!")

Predictions completed!

In [ ]:
comparison_df = pd.DataFrame({
    "Actual Genre": y_test.values[:20],
    "Naive Bayes": nb_pred[:20],
    "Logistic Regression": logistic_pred[:20],
    "SVM": svm_pred[:20]
})

comparison_df

,Actual Genre,Naive Bayes,Logistic Regression,SVM
0,"L.R. Brane loves his life - his car, his apart...",drama,short,short
1,"Spain, March 1964: Quico is a very naughty chi...",drama,short,short
2,One year in the life of Albin and his family o...,drama,short,short
3,"His father has died, he hasn't spoken with his...",drama,short,short
4,Before he was known internationally as a marti...,drama,short,short
5,Emily Burns is being held captive in a room wi...,drama,short,short
6,The beautiful but neglected wife of a brillian...,drama,short,short
7,Vasu Inamdar (Ina) suffers from a disorder whe...,drama,short,short
8,An insight into the tornados that hit Kensal R...,drama,short,short
9,Press is a story of young people overwhelmed b...,drama,short,short
10,Not much is known about the firm for which bus...,drama,short,short
11,"After a year traveling the world, twentysometh...",drama,short,short
12,"Young-ja initially mocks the shy, introverted ...",drama,short,short
13,"Mark Chambers, a down and out former professio...",drama,short,short
14,On the night a husband finally brings himself ...,drama,short,short
15,Ex-Formula 1 rookie of the year and Motor Raci...,drama,short,short
16,Ma and Pa do their bit to hook lumberman Brad ...,drama,short,short
17,"Bob Wiley, a veteran and a patriot, discovers ...",drama,short,short
18,"Eugen Sandow was a German strongman, circus pe...",drama,short,short
19,Joseph Jacoby introduces himself. He's a write...,drama,short,short

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(name, y_true, y_pred):
    return {
        "Model": name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(
            y_true, y_pred,
            average="weighted",
            zero_division=0
        ),
        "Recall": recall_score(
            y_true, y_pred,
            average="weighted",
            zero_division=0
        ),
        "F1-Score": f1_score(
            y_true, y_pred,
            average="weighted",
            zero_division=0
        )
    }

results = [
    evaluate_model("Naive Bayes", y_test, nb_pred),
    evaluate_model("Logistic Regression", y_test, logistic_pred),
    evaluate_model("SVM", y_test, svm_pred)
]

results_df = pd.DataFrame(results).sort_values(
    "F1-Score",
    ascending=False
)

results_df

                 Model  Accuracy  Precision  Recall  F1-Score
0          Naive Bayes       0.0        0.0     0.0       0.0
1  Logistic Regression       0.0        0.0     0.0       0.0
2                  SVM       0.0        0.0     0.0       0.0

In [ ]:
best_model_name = results_df.iloc[0]["Model"]

print("Best Model:", best_model_name)
print("Best F1-Score:", results_df.iloc[0]["F1-Score"])

Best Model: Naive Bayes
Best F1-Score: 0.0

In [12]:
model_dict = {
    "Naive Bayes": naive_bayes_model,
    "Logistic Regression": logistic_model,
    "SVM": svm_model
}

best_model = model_dict[best_model_name]

print("Selected model:", best_model_name)

NameError: name 'naive_bayes_model' is not defined

In [13]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Get predictions of the best model
best_pred_dict = {
    "Naive Bayes": nb_pred,
    "Logistic Regression": logistic_pred,
    "SVM": svm_pred
}

best_pred = best_pred_dict[best_model_name]

# Show number of unique genres
print("Number of unique genres:", y_test.nunique())
print("Genres:", sorted(y_test.unique()))

# Create confusion matrix
cm = confusion_matrix(y_test, best_pred)

print("Confusion Matrix Shape:", cm.shape)

# Plot confusion matrix
fig, ax = plt.subplots(figsize=(12, 10))

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

disp.plot(
    ax=ax,
    xticks_rotation=45,
    colorbar=False
)

plt.title(f"{best_model_name} - Confusion Matrix")
plt.tight_layout()
plt.show()

NameError: name 'nb_pred' is not defined

In [ ]:
print("Number of unique genres:", y_test.nunique())
print("\nGenre counts:")
print(y_test.value_counts())

Number of unique genres: 54072

Genre counts:
genre
Grammy - music award of the American academy of the audio recording, was founded by the American association of sound-recording companies of March, 14, 1958. Grammy is awarded annually as a result of voting by the authorized members of "Recording Academy".                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            10
A retired professor has returned to his estate to live with his beautiful young wife, Yelena. The estate originally belonged to his first wife, now deceased; her mother and brother still live there and manage the farm. For many years the brother (Uncle Vanya) has sent the farm's proceeds to the professor, while receiving only a small salary himself. Sonya, the professor's daughter, who is about the same age as his new wife, also lives on the estate. The professor is pompous, vain, and irritable. He calls the doctor (Astrov) to treat his gout, only to send him away without seeing him. Astrov is an experienced physician who performs his job conscientiously, but has lost all idealism and spends much of his time drinking. The presence of Yelena introduces a bit of sexual tension into the household. Astrov and Uncle Vanya both fall in love with Yelena; she spurns them both. Meanwhile, Sonya is in love with Astrov, who fails even to notice her. Finally, when the professor announces he wants to sell the estate, Vanya, whose admiration for the man died with his sister, tries to kill him.     9
The Pickwick Club sends Mr. Pickwick and a group of friends to travel across England and to report back on the interesting things they find. In the course of their travels, they repeatedly encounter the friendly but disreputable Mr. Jingle, who becomes a continual source of trouble for all who know him. Pickwick himself is the victim of a number of misunderstandings that bring him both embarrassment and problems with the law.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                7
Viola and Sebastian are lookalike twins, separated by a shipwreck. Viola lands in Illyria, where she disguises herself like her brother and goes into the service of the Duke Orsino. Orsino sends her to help him woo the Lady Olivia, who doesn't want the Duke, but finds that she likes the new messenger the Duke's sending. Then, of course, Viola's brother shows up, and merry hell breaks loose. Meanwhile, Olivia's uncle and his cohorts are trying to find some way to get back at Olivia's officious majordomo, Malvolio.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       6
Award of the American academy of cinematographic arts and sciences, from 1940th known as "Oscar", - American film award created in 1929 and traditionally handed to the figures of cinematographic art for their contribution to creation of movies.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ..
Covering multiple genres, Tales of Light & Dark is an anthology web series by Light & Dark Productions that explores the light and dark side of humanity. Episode 1: Lolli Girl - The misadventures of a young British woman whose only want in life is to find a friend. Episode 2: Open Call - For years, Mary David has yearned to escape the dreary boredom of being a housewife. Now Mary is about to get the opportunity of her life. Episode 3: Truth, Justice and the American Way - Father Peter's faith and morality is put to the test after the tragic death of a young woman. Episode 4: GeoKilling - A group of friends go geocaching and find an unusual surprise waiting for them at the end of their quest.                                                                                                                                                                                                                                                                                                                                                                                                                 1
As Alice and Cora Munro attempt to find their father, a British officer in the French and Indian War, they are set upon by French soldiers and their cohorts, Huron tribesmen led by the evil Magua. Fighting to rescue the women are Chingachgook and his son Unkas, the last of the Mohican tribe, and their white ally, the frontiersman Natty Bumppo, known as Falkenauge.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
A movie 169 years in the making. Oliver Twist, the Artful Dodger, and Fagin. The lovers will love Fagin's waifs. Plus, there's Mr. Bumble and the hairy-chested Detective Brownlow. It's 2007, the location is South Beach FL, Fagin is a pimp and his boys are whores. But that co-dependent bitch Nancy still gets it in the end!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
Popular, but mysterious rock D.J Mike Mallard (Askew) (who broadcasts his show from an isolated farmhouse) is one day found by a four young people who land their plane nearby his farm. One of them, Kathy (Oatman), falls for Mallard who is also battling with his producer (Rill) over his refusal to play the commercial music that the radio station and record companies want him to play.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
Curitiba is a city in movement, with rhythms and different pulsations, a great composed mosaic for fragments of different colors and sizes, that coexist, however nor always are touched. A city of contrasts, light and darkness, indifference and solidarity, errors and repentances. It's the coldest week on Curitiba's winter. The scenery where faces pass for the windows of the cars and people divide the sidewalk without its looks if cross, that four histories are counted on four men who have their lives transformed when the conscience talk louder than the survival instinct.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
Name: count, Length: 54072, dtype: int64